name: CI/CD Pipeline - Production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Gradle 7.4.2
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '7.4.2'

      - name: Create firebaseKey.json
        run: |
          echo "${{ secrets.FIREBASE_KEY }}" > src/main/resources/firebaseKey.json

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t agusgabrielli/buddy:prod --build-arg JAR_FILE=build/libs/*.jar --build-arg PORT=${{ vars.PORT }} .
          docker push agusgabrielli/buddy:prod