name: Java CI

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Gradle 7.4.2
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '7.4.2'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build